// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  planeSidebar: [{type: 'autogenerated', dirName: '01_plane'}],
  droneSidebar: [{type: 'autogenerated', dirName: '02_drone'}],
  carSidebar: [{type: 'autogenerated', dirName: '03_car'}],
  controllerSidebar: [{type: 'autogenerated', dirName: '04_controller'}],
  simulatorSidebar: [{type: 'autogenerated', dirName: '05_simulator'}],
  threeDimSidebar: [{type: 'autogenerated', dirName: '06_3d'}],
  faqSidebar: [{type: 'autogenerated', dirName: '99_faq'}],
};

export default sidebars;
